---
title: E80 Poster Session Agenda
---

The following document describes the agenda for the E80 poster session.

## Set Up Phase (4:00 – 4:15 pm)

1. Gather with your project team in the Outdoor Tents.  
2. Make your personal name badge using the available supplies.
3. Find a poster board location to display your poster.

## Presentation Phase I (4:15 – 4:45 pm)

1. Half of team: remain at their poster  
2. Other half of team: visit peer posters  
   - You must visit and peer review at least three posters, one from each section  
   - You may not visit a poster that presently has three visitors  
3. Bell will ring every five minutes at which point you must rotate to a new poster.

## Presentation Phase II (4:45 – 5:15 pm)

Repeat Phase I with team members switching roles.
Half of team remains at their poster and other half visit peer posters.

## Clean Up Phase (5:15 – 5:30 pm)

1. Take down your poster  
2. Vote in poster contests:  
   - Student’s Choice Awards  
   - Instructor’s Choice Awards  
3. Complete the poster session reflection form
